name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        gradle-version:
          - 9.5.0 # the latest release that is tested with Kotlin 2.3.20 (Kotlin Language Level 2.3)
          - 8.14.4 # the latest release that is tested with Kotlin 2.0.21 (Kotlin Language Level 1.8)
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: 17
      - uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: ${{ matrix.gradle-version }}
      - run: ./gradlew build
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: report-${{ matrix.gradle-version }}
          path: build/reports
